language: php
php:
  - '7.0'
before_script:
  - composer install --prefer-source
  - psql -U postgres -c 'create database didbot_test;'
  - psql -U postgres didbot_test -c 'create extension postgis;'
script: phpunit
services:
  - postgresql
addons:
  postgresql: "9.4"
